#!/usr/bin/env bash
# Sinh file env đầy đủ cho Langfuse Docker (secrets + headless init LANGFUSE_INIT_*).
# Docs: https://langfuse.com/self-hosting/administration/headless-initialization
#
# Dùng lần đầu (DB Langfuse còn trống):
# Ghi file an toàn (không dùng `npm run … > .env.langfuse`):
#   npm run langfuse:env
#   hoặc: bash scripts/gen-langfuse-seed.sh > .env.langfuse
#
# Điền vào .env của video-maker (cùng giá trị với project seed):
#   LANGFUSE_PUBLIC_KEY = LANGFUSE_INIT_PROJECT_PUBLIC_KEY
#   LANGFUSE_SECRET_KEY = LANGFUSE_INIT_PROJECT_SECRET_KEY
#   LANGFUSE_BASE_URL=http://127.0.0.1:3030
#
set -euo pipefail

rand_hex() { openssl rand -hex "$1"; }
rand_b64() { openssl rand -base64 32 | tr -d '\n'; }
rand_pw() { openssl rand -base64 48 | tr -d '\n+/=' | cut -c1-32; }

NEXTAUTH_SECRET="$(rand_b64)"
SALT="$(rand_hex 16)"
ENCRYPTION_KEY="$(rand_hex 32)"
POSTGRES_PASSWORD="$(rand_pw)"
CLICKHOUSE_PASSWORD="$(rand_pw)"
REDIS_AUTH="$(rand_pw)"
MINIO_ROOT_PASSWORD="$(rand_pw)"
INIT_USER_PASSWORD="$(rand_pw)"
LF_PK="lf_pk_$(rand_hex 16)"
LF_SK="lf_sk_$(rand_hex 32)"

cat <<SEEDEOF
# Generated by scripts/gen-langfuse-seed.sh — không commit. UI: http://localhost:3030
NEXTAUTH_URL=http://localhost:3030
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

SALT=${SALT}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

POSTGRES_USER=postgres
POSTGRES_DB=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres

CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

REDIS_AUTH=${REDIS_AUTH}

MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=\${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=\${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=minio
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=\${MINIO_ROOT_PASSWORD}

LANGFUSE_INIT_ORG_ID=ma-chu-local
LANGFUSE_INIT_ORG_NAME=Ma Chu Local
LANGFUSE_INIT_PROJECT_ID=video-maker
LANGFUSE_INIT_PROJECT_NAME=Ma Chu Video Maker
LANGFUSE_INIT_USER_EMAIL=admin@localhost.local
LANGFUSE_INIT_USER_NAME=Admin
LANGFUSE_INIT_USER_PASSWORD=${INIT_USER_PASSWORD}
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${LF_PK}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${LF_SK}
SEEDEOF

echo >&2 ""
echo >&2 "=== Ghi vào .env của video-maker ==="
echo >&2 "LANGFUSE_BASE_URL=http://127.0.0.1:3030"
echo >&2 "LANGFUSE_PUBLIC_KEY=${LF_PK}"
echo >&2 "LANGFUSE_SECRET_KEY=${LF_SK}"
echo >&2 ""
echo >&2 "=== Đăng nhập UI Langfuse ==="
echo >&2 "  email: admin@localhost.local"
echo >&2 "  password: (giá trị LANGFUSE_INIT_USER_PASSWORD trong file .env.langfuse)"
